### ISSUE TITLE
[TRACKING] 1.0 Release Blockers

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/houseform#8]
# Code

- [x] Stricter/more accurate TS types

# Docs

- [x] Non-Text Inputs
- [x] Nested Field Values
- [x] Access Data Externally
- [x] Form Arrays
- [x] TypeScript
- [x] Comparison to X
    - [x] Benchmarks

- [ ] Update CONTRIBUTING.md guide to show high-level codebase infrastructure using tldraw 

# Infrastructure

- [x] Create PR template
- [x] Create issue template
- [ ] Create CHANGELOG.md generation
